
server:
  port: 9020
  error:
    include-stacktrace: never
spring:
  application:
    name: underwriting-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 1234
    url: 'jdbc:postgresql://localhost:5432/underwritingdb'
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  file:
    name: D:\\logs\\underwriting-service.log
  pattern:
    console: "%d %-5level %logger : %msg%n" 
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  
  level:
    ROOT: INFO  
    
eureka:
 instance:
  prefer-ip-address: true
  appname: underwriting-service
 client:
   fetch-registry: true
   register-with-eureka: true
   serviceUrl:
      defaultZone: http://localhost:8761/eureka/
         
